version: "3"

services:
  file:
    build: 
      dockerfile: ./src/fileserver/Dockerfile
      context: ./
    volumes:
      - ./files:/files
      - ./logs:/logs
    environment:
      - FILES_FOLDER="/files"
      - LOGFILE="/logs/logs"
    env_file:
      - ./docker-variables.env
    networks:
      - files
  main:
    build: 
      dockerfile: ./src/mainserver/Dockerfile
      context: ./
    ports:
      - "8080:8080"
    env_file:
      - ./docker-variables.env
    networks:
      - files
    links:
      - file
networks:
  files:
    driver: bridge