version: "3"

services:
  file:
    build: 
      dockerfile: ./src/fileserver/Dockerfile
      context: ./
    volumes:
      - ./files:/files
    environment:
      - FILES_FOLDER=/files
      - CACHE_CAPACITY=0
    env_file:
      - ./docker-variables.env
    networks:
      - files
  main:
    build: 
      dockerfile: ./src/mainserver/Dockerfile
      context: ./
    ports:
      - "8080:8080"
    env_file:
      - ./docker-variables.env
    volumes:
      - ./logs:/logs
    environment:
      - LOGFILE=/logs/logs
      - NUMBER_OF_RESPONDERS=25
      - NUMBER_OF_PROCESSERS=25
    networks:
      - files
    links:
      - file
networks:
  files:
    driver: bridge
